name: lat_lon_grid_plugin
description: Adds a latitude / longitude grid as plugin to the [flutter_map](https://github.com/johnpryan/flutter_map/).
version: 0.1.1
homepage: https://github.com/mat8854/
repository: https://github.com/mat8854/lat_lon_grid_plugin

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # BSD
  flutter_map: ^0.10.1
   # git:
   #   url: https://github.com/moovida/flutter_map.git
   #   ref: version4smash

  latlong: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
